version: '3'
services:
  bank-web:
    image: hub.ferumflex.com/ferumflex/bank:prod
    environment:
      - SERVER=prod
    volumes:
      - /data/bank/bank_media:/opt/django/persistent/media
    depends_on:
      - bank-postgres
      - bank-redis
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
      labels:
        - "traefik.enable=true"
        - "traefik.backend=bank"
        - "traefik.frontend.rule=Host:bank.ferumflex.com"
        - "traefik.docker.network=traefik_frontend"
        - "traefik.port=80"
    networks:
      - backend
      - traefik_frontend

  bank-postgres:
    image: mdillon/postgis:10
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 512M
    environment:
      - POSTGRES_PASSWORD=bank777222
      - POSTGRES_USER=bank
      - POSTGRES_DB=bank
    volumes:
      - '/data/bank/postgresql_data:/var/lib/postgresql/data'
    networks:
      - backend

  bank-redis:
    image: redis
    command: redis-server --stop-writes-on-bgsave-error no
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 256M
    networks:
      - backend

  bank-worker:
    command: celery -A www worker -B -E
    image: hub.ferumflex.com/ferumflex/bank:prod
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
    environment:
      - SERVER=prod
      - C_FORCE_ROOT=1
    depends_on:
      - bank-postgres
      - bank-redis
    volumes:
      - /data/bank/bank_media:/opt/django/persistent/media
    networks:
      - backend

networks:
  backend:
  traefik_frontend:
    external: true