# Generated by Django 2.1.1 on 2018-09-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('chb_date', models.DateTimeField()),
                ('trans_date', models.DateTimeField()),
                ('atm', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=100)),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(max_length=20)),
                ('disp_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('auth_code', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('successful', 'Successful'), ('atm_no_resp', 'ATM no response'), ('dispense_error', 'Dispense error')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
