# Generated by Django 2.1.1 on 2018-10-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20180927_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='card',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
