# Generated by Django 2.1.1 on 2018-10-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_transaction_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='utrnno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
