# Generated by Django 2.1.1 on 2018-10-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_transaction_utrnno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='result',
            field=models.CharField(blank=True, choices=[('successful', 'Successful'), ('failed', 'Failed'), ('neutral', 'Neutral')], db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='utrnno',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterIndexTogether(
            name='transaction',
            index_together={('utrnno', 'report')},
        ),
    ]
