# Generated by Django 2.1.1 on 2018-10-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_auto_20181002_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='log_hash',
            field=models.CharField(db_index=True, max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('error', 'Error'), ('finished', 'Finished')], db_index=True, default='new', max_length=100),
        ),
    ]
