# Generated by Django 2.1.7 on 2019-03-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_auto_20181016_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='log_hash',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True),
        ),
    ]
