# Generated by Django 2.1.7 on 2019-03-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_auto_20190308_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined')], max_length=20, null=True),
        ),
    ]
