# Generated by Django 2.1.7 on 2019-05-08 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_stamp_select',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deadline_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='scoring',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pended', 'Pended')], max_length=20, null=True),
        ),
    ]
