# Generated by Django 2.1.7 on 2019-06-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_report_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('magazine1_amount', models.IntegerField(default=0)),
                ('magazine2_amount', models.IntegerField(default=0)),
                ('magazine3_amount', models.IntegerField(default=0)),
                ('magazine4_amount', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
