# Generated by Django 2.1.7 on 2019-06-14 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_atm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='atm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.ATM'),
        ),
    ]
