# Generated by Django 2.1.7 on 2019-06-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_auto_20190614_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='magazine1_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='magazine2_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='magazine3_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='magazine4_amount',
            field=models.IntegerField(default=0),
        ),
    ]
