# Generated by Django 2.2.5 on 2019-10-01 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_auto_20190614_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chargeback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('queue_name', models.CharField(max_length=100)),
                ('claim_id', models.CharField(max_length=100, unique=True)),
                ('pan', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=200)),
                ('acquirer_ref_num', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=100)),
                ('card_acceptor_terminal_id', models.CharField(max_length=100)),
                ('authorization_date_and_time', models.CharField(max_length=100)),
                ('result', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pend', 'Pend')], max_length=100, null=True)),
                ('result_date', models.DateTimeField(null=True)),
                ('atm_transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='bank.Transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargebackDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('reason_code', models.CharField(max_length=100)),
                ('chargeback_type', models.CharField(max_length=100)),
                ('chargeback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargeback_detail', to='bank.Chargeback')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
