# Generated by Django 2.2.5 on 2019-10-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_chargeback_chargebackdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chargeback',
            name='result',
        ),
        migrations.RemoveField(
            model_name='chargeback',
            name='result_date',
        ),
        migrations.AddField(
            model_name='chargebackdetail',
            name='result',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pend', 'Pend')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chargebackdetail',
            name='result_date',
            field=models.DateTimeField(null=True),
        ),
    ]
