# Generated by Django 3.0.8 on 2020-08-04 17:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('magazine1_amount', models.IntegerField(default=0)),
                ('magazine2_amount', models.IntegerField(default=0)),
                ('magazine3_amount', models.IntegerField(default=0)),
                ('magazine4_amount', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chargeback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('queue_name', models.CharField(max_length=100)),
                ('claim_id', models.CharField(max_length=100, unique=True)),
                ('pan', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=200)),
                ('acquirer_ref_num', models.CharField(max_length=100)),
                ('due_date', models.CharField(max_length=100)),
                ('card_acceptor_terminal_id', models.CharField(max_length=100)),
                ('authorization_date_and_time', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('acquirer_id', models.CharField(max_length=100)),
                ('acquirer_ref_num', models.CharField(max_length=200)),
                ('primary_account_num', models.CharField(max_length=100)),
                ('claim_id', models.CharField(max_length=100, unique=True)),
                ('clearing_due_date', models.DateField()),
                ('clearing_network', models.CharField(max_length=20)),
                ('due_date', models.DateField()),
                ('is_accurate', models.BooleanField()),
                ('is_acquirer', models.BooleanField()),
                ('is_issuer', models.BooleanField()),
                ('is_open', models.BooleanField()),
                ('issuer_id', models.CharField(max_length=100)),
                ('last_modified_by', models.CharField(max_length=100)),
                ('last_modified_date', models.DateTimeField()),
                ('merchant_id', models.CharField(max_length=100)),
                ('progress_state', models.CharField(max_length=100)),
                ('claim_value', models.CharField(max_length=100)),
                ('queue_name', models.CharField(max_length=100)),
                ('create_date', models.DateField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('claim_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('log', models.FileField(upload_to='logs/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('new', 'New'), ('error', 'Error'), ('finished', 'Finished')], db_index=True, default='new', max_length=100)),
                ('error', models.TextField(blank=True, null=True)),
                ('log_hash', models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('chb_date', models.DateTimeField(blank=True, null=True)),
                ('trans_date', models.DateTimeField(blank=True, null=True)),
                ('pan', models.CharField(blank=True, max_length=100, null=True)),
                ('trans_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('disp_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('auth_code', models.CharField(blank=True, max_length=100, null=True)),
                ('result', models.CharField(blank=True, choices=[('successful', 'Successful'), ('failed', 'Failed'), ('neutral', 'Neutral')], db_index=True, max_length=100, null=True)),
                ('card', models.CharField(blank=True, max_length=100, null=True)),
                ('utrnno', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('raw', models.TextField(null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pended', 'Pended')], max_length=20, null=True)),
                ('deadline_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('date_stamp_select', models.DateTimeField(blank=True, null=True)),
                ('scoring', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('magazine1_amount', models.IntegerField(default=0)),
                ('magazine2_amount', models.IntegerField(default=0)),
                ('magazine3_amount', models.IntegerField(default=0)),
                ('magazine4_amount', models.IntegerField(default=0)),
                ('atm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.ATM')),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.Report')),
            ],
            options={
                'index_together': {('utrnno', 'report')},
            },
        ),
        migrations.CreateModel(
            name='ChargebackDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('reason_code', models.CharField(max_length=100)),
                ('chargeback_type', models.CharField(max_length=100)),
                ('result', models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pend', 'Pend')], max_length=100, null=True)),
                ('chargeback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chargeback_detail', to='bank.Chargeback')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='chargeback',
            name='atm_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='bank.Transaction'),
        ),
    ]
