# Generated by Django 3.0.8 on 2020-08-21 09:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_claim_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='claim_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, help_text='Available fields: id, create_date, update_date, user_id, mediator_id, chargeback_officer_id, issuer_mmt, dispute_mmt, ch_mmt, merchant_mmt, source, arn, flag, merch_id, merch_name_ips, merchant_id, bank_id, term_id, terminal_id, trans_amount, trans_currency, trans_approval_code, trans_date, transaction_id, pan, claim_reason_code_id, reason_code_group, reason_code, action_needed, stage, status_id, result, support, answers, due_date, dispute_date, registration_date, final_date, chargeback_date, second_presentment_date, pre_arbitration_date, pre_arbitration_response_date, arbitration_date, arbitration_response_date, ', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('top_level', 'Top level'), ('security_officer', 'Security officer'), ('cop_manager', 'COP manager'), ('cardholder', 'Cardholder'), ('chargeback_officer', 'Chargeback officer'), ('merchant', 'Merchant'), ('сс_branch', 'сс/branch')], max_length=999),
        ),
    ]
