# Generated by Django 3.0.8 on 2020-08-25 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200825_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unit',
        ),
    ]
