# Generated by Django 3.0.8 on 2020-09-01 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200827_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='claim_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, help_text='Available fields: id, create_date, update_date, form_name, officer_answer_reason, user_id, replier_id, chargeback_officer_id, issuer_mmt, acquirer_mmt, dispute_mmt, ch_mmt, merchant_mmt, source, arn, flag, atm_id, merch_id, merch_name_ips, merchant_id, bank_id, term_id, terminal_id, trans_amount, trans_currency, trans_approval_code, trans_date, transaction_id, pan, claim_reason_code_id, reason_code_group, reason_code, action_needed, status_id, result, support, answers, reminder_task_ids, due_date, dispute_date, registration_date, final_date, chargeback_date, second_presentment_date, pre_arbitration_date, pre_arbitration_response_date, arbitration_date, arbitration_response_date, archived, ', null=True, size=None),
        ),
    ]
