# Generated by Django 3.0.8 on 2020-09-02 14:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200902_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='claim_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=['id', 'pan', 'trans_date', 'term_id', 'terminal', 'merchant', 'merch_id', 'merch_name_ips', 'trans_amount', 'trans_currency', 'trans_approval_code', 'claim_reason_code', 'status', 'result', 'due_date', 'action_needed'], size=None),
        ),
    ]
