# Generated by Django 3.0.8 on 2020-09-02 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200902_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='claim_fields',
            new_name='displayable_claim_fields',
        ),
    ]
