# Generated by Django 3.0.8 on 2020-09-03 18:37

import cop.users.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_password_change_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='displayable_claim_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), default=cop.users.models.get_claim_default_display_fields, size=None),
        ),
    ]
