# Generated by Django 3.0.8 on 2020-08-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200806_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='stage',
            name='stage',
            field=models.CharField(choices=[('pre_mediation', 'pre_mediation'), ('mediation', 'mediation'), ('chargeback', 'chargeback'), ('chargeback_escalation', 'chargeback_escalation')], default='pre_mediation', max_length=999),
        ),
    ]
