# Generated by Django 3.0.8 on 2020-09-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_auto_20200904_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reasoncodegroup',
            old_name='group',
            new_name='group_mastercard',
        ),
        migrations.AddField(
            model_name='reasoncodegroup',
            name='group_visa',
            field=models.CharField(blank=True, choices=[('fraud', 'Fraud'), ('authorization', 'Authorization'),
                                                        ('point_of_interaction_error', 'Point-of-Interaction Error'),
                                                        ('cardholder_disputes', 'Cardholder Disputes')], max_length=128,
                                   null=True),
        ),
    ]
