# Generated by Django 3.0.8 on 2020-08-07 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_stage_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='merch_id',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='pan',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='term_id',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='banks', to='core.Bank'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merchants', to='core.Merchant'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminals', to='core.Terminal'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.Transaction'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='terminal_id',
            field=models.CharField(max_length=999, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='merchant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Merchant'),
        ),
    ]
