# Generated by Django 3.0.8 on 2020-09-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_auto_20200904_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='hidden_pan',
            field=models.CharField(default='111111******1111', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='pan',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='claim',
            name='result',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
