# Generated by Django 3.0.8 on 2021-05-14 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200905_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankBin',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('bin', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('product_code', models.CharField(blank=True, max_length=999, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='core.Bank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
