# Generated by Django 3.0.8 on 2021-03-30 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200905_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='bin',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='type',
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('bin', models.CharField(max_length=8, unique=True)),
                ('type', models.CharField(choices=[('ACQ', 'ACQ'), ('ISS', 'ISS'), ('BOTH', 'BOTH')], max_length=4)),
                ('product_code', models.CharField(max_length=3)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bank')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
