# Generated by Django 3.0.8 on 2021-04-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200905_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('type_license', models.CharField(blank=True, choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('custom', 'Custom')], max_length=32, null=True)),
                ('license_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('implemented_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_user_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_officer_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('officers_before_cost_up', models.IntegerField(blank=True, null=True)),
                ('per_officer_up_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_merchant_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('merchants_before_cost_up', models.IntegerField(blank=True, null=True)),
                ('per_merchant_up_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_atm_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_pre_mediation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pre_mediation_before_cost_up', models.IntegerField(blank=True, null=True)),
                ('per_pre_mediation_up_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_mediation_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mediation_before_cost_up', models.IntegerField(blank=True, null=True)),
                ('per_mediation_up_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_chargeback_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('chargeback_before_cost_up', models.IntegerField(blank=True, null=True)),
                ('per_chargeback_up_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('per_us_on_us_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('us_on_us_before_cost_up', models.IntegerField(blank=True, null=True)),
                ('per_us_on_us_up_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
