# Generated by Django 3.0.8 on 2021-04-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.License'),
        ),
    ]
