# Generated by Django 3.0.8 on 2021-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='bin',
            field=models.CharField(default='00000000', max_length=8, unique=True),
        ),
        migrations.AddField(
            model_name='bank',
            name='type',
            field=models.CharField(choices=[('ACQ', 'ACQ'), ('ISS', 'ISS'), ('BOTH', 'BOTH')], default='ACQ', max_length=4),
        ),
        migrations.DeleteModel(
            name='Bin',
        ),
    ]
