# Generated by Django 3.0.8 on 2021-04-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210414_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bin',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='type',
            field=models.CharField(choices=[('ACQ', 'ACQ'), ('ISS', 'ISS'), ('BOTH', 'BOTH')], max_length=4),
        ),
    ]
