# Generated by Django 3.0.8 on 2020-08-12 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_documentrequest_reasoncodegroup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='telephone',
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='reason_code_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ReasonCodeGroup'),
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='bank',
        ),
        migrations.AddField(
            model_name='merchant',
            name='bank',
            field=models.ManyToManyField(blank=True, to='core.Bank'),
        ),
    ]
