# Generated by Django 3.0.8 on 2021-04-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210414_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action',
            field=models.CharField(choices=[('create', 'create'), ('escalation', 'escalation'), ('close', 'close')], default='create', max_length=10),
            preserve_default=False,
        ),
    ]
