# Generated by Django 3.0.8 on 2020-08-13 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200812_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claim_reason_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ReasonCodeGroup'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='reason_code',
            field=models.CharField(blank=True, help_text='IPS code', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='reason_code_group',
            field=models.CharField(blank=True, help_text='Code description', max_length=999, null=True),
        ),
    ]
