# Generated by Django 3.0.8 on 2020-08-13 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200813_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='claim_reason_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ReasonCodeGroup'),
            preserve_default=False,
        ),
    ]
