# Generated by Django 3.0.8 on 2020-08-13 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200813_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('substitute_draft', 'Substitute Draft'), ('check', 'Check'), ('compelling_evidence', 'Compelling evidence'), ('docs_not_needed', 'Docs not needed')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='claim-documents/')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Claim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
