# Generated by Django 3.0.8 on 2020-08-13 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200813_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocument',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.Claim'),
        ),
    ]
