# Generated by Django 3.0.8 on 2021-05-07 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_chatsettings_message_messagefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsettings',
            name='claim',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to='core.Claim'),
            preserve_default=False,
        ),
    ]
