# Generated by Django 3.0.8 on 2020-08-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200813_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='bin',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
