# Generated by Django 3.0.8 on 2020-08-14 10:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200814_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('magazine1_amount', models.IntegerField(default=0)),
                ('magazine2_amount', models.IntegerField(default=0)),
                ('magazine3_amount', models.IntegerField(default=0)),
                ('magazine4_amount', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('log', models.FileField(upload_to='logs/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('new', 'New'), ('error', 'Error'), ('finished', 'Finished')], db_index=True, default='new', max_length=100)),
                ('error', models.TextField(blank=True, null=True)),
                ('log_hash', models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='auth_code',
        ),
        migrations.AddField(
            model_name='transaction',
            name='disp_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='magazine1_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='magazine2_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='magazine3_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='magazine4_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='raw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='scoring',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('declined', 'Declined'), ('pended', 'Pended')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='utrnno',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='result',
            field=models.CharField(blank=True, choices=[('successful', 'Successful'), ('failed', 'Failed'), ('neutral', 'Neutral')], db_index=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='DocumentRequest',
        ),
        migrations.AddField(
            model_name='transaction',
            name='atm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ATM'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Report'),
        ),
    ]
