# Generated by Django 3.0.8 on 2020-08-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200814_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='trans_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='atm',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='status',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pan',
            field=models.CharField(default=2222222222222222, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='result',
            field=models.CharField(blank=True, db_index=True, max_length=999, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_date',
            field=models.DateTimeField(blank=True, max_length=12, null=True),
        ),
        migrations.DeleteModel(
            name='ATM',
        ),
    ]
