# Generated by Django 3.0.8 on 2020-08-14 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_auto_20200814_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='claim_document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.ClaimDocument'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
