# Generated by Django 3.0.8 on 2020-08-14 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200814_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Report'),
        ),
    ]
