# Generated by Django 3.0.8 on 2020-08-17 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200814_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='name_ips',
            field=models.CharField(default='test', max_length=999),
            preserve_default=False,
        ),
    ]
