# Generated by Django 3.0.8 on 2020-08-17 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200817_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='pan',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
    ]
