# Generated by Django 3.0.8 on 2020-08-17 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200817_0804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='bank_comments_a',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='bank_comments_i',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='ch_comments',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='merchant_comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='claim',
            field=models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.Claim'),
            preserve_default=False,
        ),
    ]
