# Generated by Django 3.0.8 on 2020-08-18 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200817_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocument',
            name='type',
            field=models.CharField(choices=[('substitute_draft', 'Substitute Draft'), ('check', 'Check'), ('compelling_evidence', 'Compelling evidence'), ('atm_log', 'ATM log'), ('docs_not_needed', 'Docs not needed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='claim_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ClaimDocument'),
        ),
    ]
