# Generated by Django 3.0.8 on 2020-08-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200820_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='index',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
