# Generated by Django 3.0.8 on 2020-08-21 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='trans_currency',
            field=models.CharField(choices=[('usd', 'дол. США'), ('eur', 'євро'), ('uah', 'грн')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'дол. США'), ('eur', 'євро'), ('uah', 'грн')], max_length=3, null=True),
        ),
    ]
