# Generated by Django 3.0.8 on 2020-08-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20200821_0948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='stage',
        ),
        migrations.AddField(
            model_name='claim',
            name='acquirer_mmt',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='form_name',
            field=models.CharField(blank=True, choices=[('escalate_form', 'escalate_form'), ('close_form', 'close_form'), ('clarify_form', 'clarify_form')], max_length=32, null=True),
        ),
    ]
