# Generated by Django 3.0.8 on 2020-08-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20200821_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
