# Generated by Django 3.0.8 on 2020-08-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200825_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocument',
            name='type',
            field=models.CharField(blank=True, choices=[('substitute_draft', 'Substitute Draft'), ('check', 'Check'), ('compelling_evidence', 'Compelling evidence'), ('atm_log', 'ATM log'), ('docs_not_needed', 'Docs not needed')], max_length=20, null=True),
        ),
    ]
