# Generated by Django 3.0.8 on 2020-08-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200825_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankemployee',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
