# Generated by Django 3.0.8 on 2020-08-27 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0036_bankemployee_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('merch_id', models.CharField(max_length=15, unique=True)),
                ('name_legal', models.CharField(blank=True, max_length=999, null=True)),
                ('bin', models.CharField(blank=True, max_length=999, null=True)),
                ('name_ips', models.CharField(max_length=999)),
                ('mcc', models.CharField(blank=True, max_length=4, null=True)),
                ('description', models.CharField(blank=True, max_length=999, null=True)),
                ('address', models.CharField(blank=True, max_length=999, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=999, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bank')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bankemployee',
            name='atm',
            field=models.ManyToManyField(related_name='bank_employees', to='core.ATM'),
        ),
    ]
