# Generated by Django 3.0.8 on 2020-08-27 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0037_auto_20200827_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='atm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ATM'),
        ),
    ]
