# Generated by Django 3.0.8 on 2020-08-28 12:43

import storages.backends.s3boto3
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0038_claim_atm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='log',
            field=models.FileField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket='coplogs'), upload_to=''),
        ),
    ]
