# Generated by Django 3.0.8 on 2020-09-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20200901_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasoncodegroup',
            name='group',
            field=models.CharField(blank=True, choices=[('fraud', 'Fraud'), ('authorization', 'Authorization'), ('point_of_interaction_error', 'Point-of-Interaction Error'), ('cardholder_disputes', 'Cardholder Disputes')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='support',
            field=models.CharField(blank=True, choices=[('us_on_them', 'Us on them'), ('them_on_us', 'Them on us'), ('us_on_us', 'Us on us')], max_length=999, null=True),
        ),
    ]
