# Generated by Django 3.0.8 on 2020-09-02 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0044_auto_20200902_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='chargeback_officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_chargeback_officers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claim_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimdocument',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
