# Generated by Django 3.0.8 on 2020-09-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20200902_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='action_needed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='claim',
            name='flag',
            field=models.CharField(blank=True, choices=[('yellow', 'Yellow'), ('red', 'Red')], max_length=12, null=True),
        ),
    ]
