# Generated by Django 3.0.8 on 2020-09-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20200902_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='action_needed',
            field=models.BooleanField(default=False),
        ),
    ]
