# Generated by Django 3.0.8 on 2020-09-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_claim_action_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='action_needed',
            field=models.BooleanField(default=False),
        ),
    ]
