# Generated by Django 3.0.8 on 2020-09-03 07:54

import cop.utils.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_claim_action_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimdocument',
            name='file',
            field=models.FileField(upload_to='claim-documents/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='log',
            field=models.FileField(storage=cop.utils.storages.LogsRootS3Boto3Storage(), upload_to=''),
        ),
    ]
